environment:
  ELM_VERSION: "0.17.1"
  nodejs_version: "6.0"

platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install
  - elm-package install --yes

test_script:
  - npm test

build: off
